version: '3.1'

services:
  endpoint:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5432:5432
    networks:
      - mynet
    environment:
      JWT_SECRET: ${JWT_SECRET}
      POSTGRESQL_CONNECTION_STRING: ${POSTGRESQL_CONNECTION_STRING}