version: '3.1'

services:
  endpoint:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    environment:
      JWT_SECRET: ${JWT_SECRET}
      
